-- MySQL Script generated by MySQL Workbench
-- Sun Aug 13 09:20:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecclesiav1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecclesiav1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecclesiav1` DEFAULT CHARACTER SET latin1 ;
USE `ecclesiav1` ;

-- -----------------------------------------------------
-- Table `ecclesiav1`.`iglesia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`iglesia` (
  `idiglesia` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombredelaiglesia` VARCHAR(120) NOT NULL,
  `identificacion` VARCHAR(15) NOT NULL,
  `direccion` MEDIUMTEXT NOT NULL,
  `telefonos` VARCHAR(50) NOT NULL,
  `fechadefundacion` DATE NOT NULL,
  `registro` MEDIUMTEXT NOT NULL,
  `horarios` MEDIUMTEXT NOT NULL,
  `documentodeconstitucion` BLOB NULL DEFAULT NULL,
  `logo` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idiglesia`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`miembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`miembros` (
  `idmiembros` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `tipodeidentificacion` SET('Nacional', 'Extranjero') NULL,
  `identificacion` VARCHAR(15) NULL,
  `razonsocial` VARCHAR(120) NULL,
  `fechanacimiento` DATE NULL,
  `direcion` MEDIUMTEXT NULL,
  `telefonos` VARCHAR(25) NULL,
  `estadocivil` SET('Casado(a)', 'Soltero(a)', 'Concuvinato', 'Divorciado', 'Viudo', 'Union de Acuerdo') NULL,
  `Conyugue` VARCHAR(120) NULL,
  `hijos` SET('No', 'Si') NULL,
  `nombreshijos` MEDIUMTEXT NULL,
  `nivelacademico` INT NULL,
  `educacion` MEDIUMTEXT NULL,
  `trabaja` SET('No', 'Si') NULL,
  `empresaactual` VARCHAR(120) NULL,
  `direccion` MEDIUMTEXT NULL,
  `telefonos2` VARCHAR(50) NULL,
  `cargo` VARCHAR(120) NULL,
  `infancia` MEDIUMTEXT NULL,
  `trasfondoreligioso` MEDIUMTEXT NULL,
  `comoconociolaiglesia` MEDIUMTEXT NULL,
  `invitacion` INT NULL,
  `fechainvitacion` DATE NULL,
  `fechaconversion` DATE NULL,
  `testimonio` MEDIUMTEXT NULL,
  `bautismo` SET('No', 'Si') NULL,
  `fechabautismo` DATE NULL,
  `lugardebautismo` VARCHAR(120) NULL,
  `bautismodeespiritu` SET('No', 'Si') NULL,
  `donesespirituales` MEDIUMTEXT NULL,
  `consejeria` SET('No', 'Si') NULL,
  `datosparaconsejeria` MEDIUMTEXT NULL,
  `activo` SET('Si', 'No') NULL,
  `notasrapidas` MEDIUMTEXT NULL,
  `participaministeriosoactividades` MEDIUMTEXT NULL,
  `liderasgo` SET('No', 'Si') NULL,
  `liderasgoen` MEDIUMTEXT NULL,
  `fechareg` DATETIME NULL,
  PRIMARY KEY (`idmiembros`))
ENGINE = InnoDB
COMMENT = 'contiene informacion general hacerca de los miembros de la iglesia es una tabla de datos filiatorios complementarias';


-- -----------------------------------------------------
-- Table `ecclesiav1`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`empresas` (
  `idempresas` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `tipo` SET('Contribuyente', 'No Contribuyente', 'Contribuyente Especial', 'Exonerado', 'Gubernamental') NULL,
  `identificacion` VARCHAR(15) NULL,
  `razonsocial` VARCHAR(120) NULL,
  `direccion` MEDIUMTEXT NULL,
  `telefonos` VARCHAR(50) NULL,
  `correoelectronico` VARCHAR(150) NULL,
  `personacontacto` VARCHAR(120) NULL,
  `fechareg` DATETIME NULL,
  PRIMARY KEY (`idempresas`))
ENGINE = InnoDB
COMMENT = 'detalla informacion de las empresas o personas que hacen vida pero que no desean ser miembro activo de la congregacion\n';


-- -----------------------------------------------------
-- Table `ecclesiav1`.`ingresosactividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`ingresosactividades` (
  `idingresosactividades` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `conceptoingreso` VARCHAR(120) NULL,
  `fecha` DATE NULL,
  `ingresonodefinido` DECIMAL(2) NULL,
  `tipodeingresonodefinido` INT NULL,
  `fechareg` DATETIME NULL,
  PRIMARY KEY (`idingresosactividades`))
ENGINE = InnoDB
COMMENT = 'detalla los ingresos por servicios o actividades tanto dentro como fuera de los establecimientos\n';


-- -----------------------------------------------------
-- Table `ecclesiav1`.`ingmiembrosactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`ingmiembrosactividad` (
  `idingmiembrosactividad` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idmiembro` INT NULL,
  `identificacion` VARCHAR(15) NULL,
  `nombre` VARCHAR(120) NULL,
  `tipoingresodefinido` INT NULL,
  `monto` DECIMAL(2) NULL,
  `fechareg` DATETIME NULL,
  `ingresosactividades_idingresosactividades` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idingmiembrosactividad`),
  INDEX `fk_ingmiembrosactividad_ingresosactividades1_idx` (`ingresosactividades_idingresosactividades` ASC),
  CONSTRAINT `fk_ingmiembrosactividad_ingresosactividades1`
    FOREIGN KEY (`ingresosactividades_idingresosactividades`)
    REFERENCES `ecclesiav1`.`ingresosactividades` (`idingresosactividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`ingempresasactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`ingempresasactividad` (
  `idingempresasactividad` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idmiembro` INT NULL,
  `identificacion` VARCHAR(15) NULL,
  `razonsocial` VARCHAR(120) NULL,
  `tipoingresodefinido` INT NULL,
  `monto` DECIMAL(2) NULL,
  `fechareg` DATETIME NULL,
  `ingresosactividades_idingresosactividades` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idingempresasactividad`),
  INDEX `fk_ingempresasactividad_ingresosactividades_idx` (`ingresosactividades_idingresosactividades` ASC),
  CONSTRAINT `fk_ingempresasactividad_ingresosactividades`
    FOREIGN KEY (`ingresosactividades_idingresosactividades`)
    REFERENCES `ecclesiav1`.`ingresosactividades` (`idingresosactividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`ingresosfueradeactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`ingresosfueradeactividad` (
  `idingresosfuerdadeactividades` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `conceptoingreso` VARCHAR(120) NULL,
  `fecha` DATE NULL,
  `ingresonodefinido` DECIMAL(2) NULL,
  `tipodeingresonodefinido` INT NULL,
  `fechareg` DATETIME NULL,
  PRIMARY KEY (`idingresosfuerdadeactividades`))
ENGINE = InnoDB
COMMENT = 'detalla los ingresos por servicios o actividades tanto dentro como fuera de los establecimientos\n';


-- -----------------------------------------------------
-- Table `ecclesiav1`.`ingmiembrosfueradeactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`ingmiembrosfueradeactividad` (
  `idingmiembrosfueradeactividad` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idmiembro` INT NULL,
  `identificacion` VARCHAR(15) NULL,
  `nombre` VARCHAR(120) NULL,
  `tipoingresodefinido` INT NULL,
  `monto` DECIMAL(2) NULL,
  `fechareg` DATETIME NULL,
  `ingresosfueradeactividad_idingresosfuerdadeactividades` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idingmiembrosfueradeactividad`),
  INDEX `fk_ingmiembrosfueradeactividad_ingresosfueradeactividad1_idx` (`ingresosfueradeactividad_idingresosfuerdadeactividades` ASC),
  CONSTRAINT `fk_ingmiembrosfueradeactividad_ingresosfueradeactividad1`
    FOREIGN KEY (`ingresosfueradeactividad_idingresosfuerdadeactividades`)
    REFERENCES `ecclesiav1`.`ingresosfueradeactividad` (`idingresosfuerdadeactividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`ingempresasfueradeactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`ingempresasfueradeactividad` (
  `idingempresasfueradeactividad` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idmiembro` INT NULL,
  `identificacion` VARCHAR(15) NULL,
  `razonsocial` VARCHAR(120) NULL,
  `tipoingresodefinido` INT NULL,
  `monto` DECIMAL(2) NULL,
  `fechareg` DATETIME NULL,
  `ingresosfueradeactividad_idingresosfuerdadeactividades` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idingempresasfueradeactividad`),
  INDEX `fk_ingempresasfueradeactividad_ingresosfueradeactividad1_idx` (`ingresosfueradeactividad_idingresosfuerdadeactividades` ASC),
  CONSTRAINT `fk_ingempresasfueradeactividad_ingresosfueradeactividad1`
    FOREIGN KEY (`ingresosfueradeactividad_idingresosfuerdadeactividades`)
    REFERENCES `ecclesiav1`.`ingresosfueradeactividad` (`idingresosfuerdadeactividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`ingresosdefinidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`ingresosdefinidos` (
  `idingresosdefinidos` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `concepto` VARCHAR(45) NULL,
  PRIMARY KEY (`idingresosdefinidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`ingresosnodefinidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`ingresosnodefinidos` (
  `idingresosnodefinidos` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `concepto` VARCHAR(45) NULL,
  PRIMARY KEY (`idingresosnodefinidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`actividadesoministerios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`actividadesoministerios` (
  `idactividadesoministerios` INT NOT NULL AUTO_INCREMENT,
  `tipo` SET('Actividades', 'Ministerios') NULL,
  `descripcion` VARCHAR(100) NULL,
  `resumen` MEDIUMTEXT NULL,
  `logo` BLOB NULL,
  PRIMARY KEY (`idactividadesoministerios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`conferencistapredicadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`conferencistapredicadores` (
  `idconferencistapredicadores` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `tipoidentificacion` SET('Nacional', 'Extrajero') NULL,
  `identificacion` VARCHAR(15) NULL,
  `rezonsocial` VARCHAR(120) NULL,
  `fechanaciomiento` DATE NULL,
  `direccion` MEDIUMTEXT NULL,
  `telefonos` VARCHAR(50) NULL,
  `correoelectronico` VARCHAR(150) NULL,
  `estudiosprofesionales` SET('Si', 'No') NULL,
  `detalleestudiospro` MEDIUMTEXT NULL,
  `estudiosreligiosos` SET('Si', 'No') NULL,
  `detalleestudiosrel` MEDIUMTEXT NULL,
  `foto` BLOB NULL,
  PRIMARY KEY (`idconferencistapredicadores`))
ENGINE = InnoDB
COMMENT = 'contiene los datos basiscos del conferencista o pastor asignado a la congregacion';


-- -----------------------------------------------------
-- Table `ecclesiav1`.`juntadirectiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`juntadirectiva` (
  `idjuntadirectiva` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idmiembros` INT NULL,
  `identificacion` VARCHAR(15) NULL,
  `razonsocial` VARCHAR(120) NULL,
  `fechanacimiento` DATE NULL,
  `direcion` MEDIUMTEXT NULL,
  `telefonos` VARCHAR(25) NULL,
  `cargo` VARCHAR(120) NULL,
  `descripcion` MEDIUMTEXT NULL,
  `fechaseleccion` DATE NULL,
  PRIMARY KEY (`idjuntadirectiva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`serviciosconferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`serviciosconferencias` (
  `idserviciosconferencias` INT ZEROFILL NOT NULL,
  `fechareg` DATETIME NULL,
  `fechaservicio` DATETIME NULL,
  `titulo` VARCHAR(120) NULL,
  `descripcion` MEDIUMTEXT NULL,
  `observacion` MEDIUMTEXT NULL,
  `documentoconf` BLOB NULL,
  `audiodesoporte` BLOB NULL,
  PRIMARY KEY (`idserviciosconferencias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`controldegruposactividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`controldegruposactividades` (
  `idcontroldegruposactividades` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `fechareg` DATETIME NULL,
  `fechaactividad` DATETIME NULL,
  `motivoreunion` VARCHAR(120) NULL,
  `responsable` MEDIUMTEXT NULL,
  `colaboradores` MEDIUMTEXT NULL,
  `asistencia` MEDIUMTEXT NULL,
  `reportedeactividad` MEDIUMTEXT NULL,
  `observaciones` MEDIUMTEXT NULL,
  `audiodedsoporte` BLOB NULL,
  PRIMARY KEY (`idcontroldegruposactividades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`controldegruposactividadesfotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`controldegruposactividadesfotos` (
  `idcontroldegruposactividadesfotos` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `foto` BLOB NULL,
  `observacion` MEDIUMTEXT NULL,
  `controldegruposactividades_idcontroldegruposactividades` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idcontroldegruposactividadesfotos`),
  INDEX `fk_controldegruposactividadesfotos_controldegruposactividad_idx` (`controldegruposactividades_idcontroldegruposactividades` ASC),
  CONSTRAINT `fk_controldegruposactividadesfotos_controldegruposactividades1`
    FOREIGN KEY (`controldegruposactividades_idcontroldegruposactividades`)
    REFERENCES `ecclesiav1`.`controldegruposactividades` (`idcontroldegruposactividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`serviciosconferenciasfotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`serviciosconferenciasfotos` (
  `idserviciosconferenciasfotos` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `foto` BLOB NULL,
  `observaciones` MEDIUMTEXT NULL,
  `serviciosconferencias_idserviciosconferencias` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idserviciosconferenciasfotos`),
  INDEX `fk_serviciosconferenciasfotos_serviciosconferencias1_idx` (`serviciosconferencias_idserviciosconferencias` ASC),
  CONSTRAINT `fk_serviciosconferenciasfotos_serviciosconferencias1`
    FOREIGN KEY (`serviciosconferencias_idserviciosconferencias`)
    REFERENCES `ecclesiav1`.`serviciosconferencias` (`idserviciosconferencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`niveledu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`niveledu` (
  `idniveledu` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NULL,
  PRIMARY KEY (`idniveledu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`escuela` (
  `idescuela` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  PRIMARY KEY (`idescuela`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`modulosescuelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`modulosescuelas` (
  `idmodulosescuelas` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `escuela_idescuela` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idmodulosescuelas`, `escuela_idescuela`),
  INDEX `fk_modulosescuelas_escuela1_idx` (`escuela_idescuela` ASC),
  CONSTRAINT `fk_modulosescuelas_escuela1`
    FOREIGN KEY (`escuela_idescuela`)
    REFERENCES `ecclesiav1`.`escuela` (`idescuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`nivelescuelamodulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`nivelescuelamodulos` (
  `idnivelescuelamodulos` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `modulosescuelas_idmodulosescuelas` INT ZEROFILL NOT NULL,
  `modulosescuelas_escuela_idescuela` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idnivelescuelamodulos`, `modulosescuelas_idmodulosescuelas`, `modulosescuelas_escuela_idescuela`),
  INDEX `fk_nivelescuelamodulos_modulosescuelas1_idx` (`modulosescuelas_idmodulosescuelas` ASC, `modulosescuelas_escuela_idescuela` ASC),
  CONSTRAINT `fk_nivelescuelamodulos_modulosescuelas1`
    FOREIGN KEY (`modulosescuelas_idmodulosescuelas` , `modulosescuelas_escuela_idescuela`)
    REFERENCES `ecclesiav1`.`modulosescuelas` (`idmodulosescuelas` , `escuela_idescuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`regclaseescuelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`regclaseescuelas` (
  `idregescuelas` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `fechadeclase` DATE NULL,
  `fechareg` DATETIME NULL,
  `idescuela` INT NULL,
  `idmoduloescuela` INT NULL,
  `idnivelescuelamodulos` INT NULL,
  `observaciones` MEDIUMTEXT NULL,
  `soportedecontenido` BLOB NULL,
  PRIMARY KEY (`idregescuelas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`regestuclasesecuelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`regestuclasesecuelas` (
  `idregestuclasesecuelas` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idmiembro` INT NULL,
  `identificacion` VARCHAR(15) NULL,
  `razonsocial` VARCHAR(120) NULL,
  `asistencia` VARCHAR(1) NULL,
  `evaluacion` DECIMAL NULL,
  `observacionesalumno` MEDIUMTEXT NULL,
  `regclaseescuelas_idregescuelas` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idregestuclasesecuelas`),
  INDEX `fk_regestuclasesecuelas_regclaseescuelas1_idx` (`regclaseescuelas_idregescuelas` ASC),
  CONSTRAINT `fk_regestuclasesecuelas_regclaseescuelas1`
    FOREIGN KEY (`regclaseescuelas_idregescuelas`)
    REFERENCES `ecclesiav1`.`regclaseescuelas` (`idregescuelas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecclesiav1`.`miembrosreg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecclesiav1`.`miembrosreg` (
  `idmiembrosreg` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idmiembros` INT ZEROFILL NOT NULL,
  `identificacion` VARCHAR(15) NOT NULL,
  `razonsocial` VARCHAR(120) NOT NULL,
  `asunto` TEXT NOT NULL,
  `fecharegistro` DATE NOT NULL,
  PRIMARY KEY (`idmiembrosreg`))
ENGINE = InnoDB;

USE `ecclesiav1`;

DELIMITER $$
USE `ecclesiav1`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `ecclesia`.`iglesia_registro`
BEFORE INSERT ON `ecclesia`.`iglesia`
FOR EACH ROW
BEGIN
SELECT COUNT(*) INTO @count FROM iglesia;
IF @count >= 1 THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Solo se puede crear una Iglesia por Licencia si tiene algun problema comuniquese con el departamento tecnico';
END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
